import { makeStyles } from "@material-ui/core";

const color = "#F9D75F";
const useStyles = makeStyles({
  container: {
    marginTop: "35px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
  },
  scoreBigroot: {
    display: "flex",
    justifyContent: "space-around",
    marginTop: "30px",
  },
  score: {
    fontSize: "3.7rem",
    color: "white",
  },
  levelBadge: (props) => ({
    backgroundColor: `${props.badgecolor}`,
    padding: "3px 2px",
    color: "white",
    borderRadius: "6px 0px",
    marginTop: "20px",
  }),
  faceDreamer: {
    color: "white",
    margin: "33px 0px 0px 0px",
  },
  awardTitle: {
    fontSize: "2.8rem",
    color: "#F9D75F",
    marginTop: "99px",
  },
  congratulation: {
    position: "relative",
    margin: "20px 0px",
    width: "250px",
  },
  congratulationScript: {
    position: "relative",
    backgroundColor: "white",
    maxWidth: "210px",
    padding: "20px",
    "&:after": {
      content: "''",
      zIndex: "5",
      position: "absolute",
      width: "0",
      height: "0",
      borderLeft: "15px solid transparent",
      borderRight: "15px solid transparent",
      borderTop: "15px solid #fff",
      bottom: "-15px",
      right: "70px",
    },
  },
  seperateLine: {
    display: "block",
    height: "1px",
    border: "0",
    borderTop: "1px solid #ccc",
    margin: "1em 0",
    padding: "0",
  },
  imgContainer: {
    marginTop: "50px",
    display: "flex",
    justifyContent: "flex-end",
  },
  awardAvatar: {},
  averageRoot: {
    position: "relative",
    marginTop: "140px",
    fontSize: "2rem",
    color: "white",
  },
  scoreBarMask: {
    zIndex: 1,
    backgroundColor: "black",
    width: "100%",
    maxWidth: "282px",
    color: "white",
    height: "20px",
    borderRadius: "70px",
    position: "relative",
    overflow: "hidden",
    clipPath: "border-box",
  },
  scoreBarBox: (props) => ({
    zIndex: -1,
    width: `${props.meter}`,
    backgroundColor: color,
    position: "absolute",
    height: "100%",
    left: 0,
    top: 0,
    transition: "width .5s ease-in-out",
  }),
  defaultBarBox: (props) => ({
    zIndex: -2,
    width: `${props.defaultMeter}`,
    backgroundColor: "white",
    position: "absolute",
    height: "100%",
    left: 0,
    top: 0,
    transition: "width .5s ease-in-out",
  }),
  creditsSection: {
    color: "white",
    "& a": {
      textDecoration: "underline",
      cursor: "pointer",
      color: "white",
    },
  },
  techIssue: {
    color: "white",
    "& p": {
      lineHeight: "1rem",
    },
  },
  /* .makeStyles-average-19::before */
  average: (props) => ({
    transition: "all 1s",
    zIndex: "3",
    position: "absolute",
    bottom: "-50px",
    left: props.defaultMeter,
    transform: "translateX(-50%)",
    "&:before": {
      content: "''",
      zIndex: "5",
      top: "-20px",
      left: "50%",
      transform: "translateX(-50%)",
      position: "absolute",
      borderLeft: "8px solid transparent",
      borderRight: "8px solid transparent",
      borderBottom: `16px solid ${color}`,
    },
  }),
  your: (props) => ({
    transition: "all 1s",
    zIndex: "3",
    color: color,
    position: "absolute",
    top: "-50px",
    left: props.meter,
    transform: "translateX(-50%) translateY(-50%)",
    "&:before": {
      content: "''",
      zIndex: "5",
      bottom: "-20px",
      left: "50%",
      transform: "translateX(-50%)",
      position: "absolute",
      borderLeft: "8px solid transparent",
      borderRight: "8px solid transparent",
      borderTop: `16px solid ${color}`,
    },
  }),
});

export default useStyles;
